export type ServerSettings = {
  config: {
    gameMode: string;
    loginTime: number;
    maxClientsPerIP: number;
    difficulty: number;
    passTimeWhenEmpty: boolean;
    nightStartHour: number;
    nightEndHour: number;
    allowConsole: boolean;
    allowBedRest: boolean;
    allowWildernessRest: boolean;
    allowWait: boolean;
    shareJournal: boolean;
    shareFactionRanks: boolean;
    shareFactionExpulsion: boolean;
    shareFactionReputation: boolean;
    shareTopics: boolean;
    shareBounty: boolean;
    shareReputation: boolean;
    shareMapExploration: boolean;
    shareVideos: boolean;
    useInstancedSpawn: boolean;
    respawnAtImperialShrine: boolean;
    respawnAtTribunalTemple: boolean;
    maxAttributeValue: number;
    maxSpeedValue: number;
    maxSkillValue: number;
    maxAcrobaticsValue: number;
    ignoreModifierWithMaxSkill: boolean;
    playersRespawn: boolean;
    deathTime: number;
    deathPenaltyJailDays: number;
    bountyResetOnDeath: boolean;
    bountyDeathPenalty: boolean;
    allowSuicideCommand: boolean;
    allowFixmeCommand: boolean;
    fixmeInterval: number;
    pingDifferenceRequiredForAuthority: number;
    enforcedLogLevel: number;
    physicsFramerate: number;
    allowOnContainerForUnloadedCells: boolean;
    enablePlayerCollision: boolean;
    enableActorCollision: boolean;
    enablePlacedObjectCollision: boolean;
    useActorCollisionForPlacedObjects: boolean;
    maximumObjectScale: number;
    enforceDataFiles: boolean;
  };
};

export const DefaultServerSettings: ServerSettings = {
  config: {
    allowBedRest: true,
    allowConsole: false,
    allowFixmeCommand: true,
    allowOnContainerForUnloadedCells: false,
    allowSuicideCommand: true,
    allowWait: true,
    allowWildernessRest: true,
    bountyDeathPenalty: false,
    bountyResetOnDeath: false,
    deathPenaltyJailDays: 5,
    deathTime: 5,
    difficulty: 0,
    enableActorCollision: true,
    enablePlacedObjectCollision: false,
    enablePlayerCollision: true,
    enforceDataFiles: true,
    enforcedLogLevel: -1,
    fixmeInterval: 30,
    gameMode: "Default",
    ignoreModifierWithMaxSkill: false,
    loginTime: 60,
    maxAcrobaticsValue: 1200,
    maxAttributeValue: 200,
    maxClientsPerIP: 3,
    maxSkillValue: 200,
    maxSpeedValue: 365,
    maximumObjectScale: 20,
    nightEndHour: 6,
    nightStartHour: 20,
    passTimeWhenEmpty: false,
    physicsFramerate: 60,
    pingDifferenceRequiredForAuthority: 40,
    playersRespawn: true,
    respawnAtImperialShrine: true,
    respawnAtTribunalTemple: true,
    shareBounty: false,
    shareFactionExpulsion: false,
    shareFactionRanks: true,
    shareFactionReputation: true,
    shareJournal: true,
    shareMapExploration: false,
    shareReputation: true,
    shareTopics: true,
    shareVideos: true,
    useActorCollisionForPlacedObjects: false,
    useInstancedSpawn: true,
  },
};
